### ISSUE TITLE
The extension is no longer on the Firefox store

### ISSUE THREAD

**Issue by Dkfc123** [onRuntime/instagram-dark-extension#14]
issue is described in the title, is there any reason why it was taken down?

**Comment by antoinekm** [comment]
> issue is described in the title, is there any reason why it was taken down?

we having issues with mozilla support but we're are trying to resolve this issue

**Comment by antoinekm** [comment]
@jerembdn can you send an email to mozilla support ?

**Comment by jerembdn** [comment]
It's sent since a week

**Comment by antoinekm** [comment]
> It's sent since a week

I think we gonna republish it

**Comment by antoinekm** [comment]
> issue is described in the title, is there any reason why it was taken down?

Done! It's back on the mozilla addons store!

https://addons.mozilla.org/fr/firefox/addon/instagram-dark-theme/

**Comment by Dkfc123** [comment]
> > issue is described in the title, is there any reason why it was taken down?
> 
> Done! It's back on the mozilla addons store!
> 
> https://addons.mozilla.org/fr/firefox/addon/instagram-dark-theme/

thanks!!
