### ISSUE TITLE
Bad display on blocked account profiles

### ISSUE THREAD

**Issue by antoinekm** [onRuntime/instagram-dark-extension#16]
![image](https://user-images.githubusercontent.com/54948363/147999748-d1eea9fc-99e8-47d5-abff-ef85e48ccab7.png)

**Comment by hyperglass** [comment]
This issue can be closed since it looks like its fixed now.

**Comment by antoinekm** [comment]
![image](https://user-images.githubusercontent.com/54948363/153761045-d1fa4e36-d837-45a2-b3f1-eea9b72b1dc6.png)
