### ISSUE TITLE
Readme Discord Invite is Invalid

### ISSUE THREAD

**Issue by antoinekm** [onRuntime/instagram-dark-extension#21]

**Comment by ramanand-rv** [comment]
Hi @AntoineKM 
Please share the valid Discord Invite link. I'll update it in the README.md file

**Comment by AntoineKM** [comment]
Thanks i'll be glad to see your PR, the discord link should be https://discord.gg/ucX9c5yXmX

**Comment by antoinekm** [comment]
> Hi @AntoineKM Please share the valid Discord Invite link. I'll update it in the README.md file

Thanks i'll be glad to see your PR, the discord link should be https://discord.gg/ucX9c5yXmX

**Comment by ramanand-rv** [comment]
Hi @AntoineKM, I've raised a pull request with the updated Discord Invite link in README file.
