### ISSUE TITLE
Add/Increase Shadows in Appropriate places

### ISSUE THREAD

**Issue by hyperglass** [onRuntime/instagram-dark-extension#34]
Increase shadow at the Menu border
![image](https://user-images.githubusercontent.com/99114709/153759821-21589c1c-04e3-44a6-b10d-c8c769ea0e14.png)
and also on post's border if possible

**Comment by antoinekm** [comment]
> Increase shadow at the Menu border ![image](https://user-images.githubusercontent.com/99114709/153759821-21589c1c-04e3-44a6-b10d-c8c769ea0e14.png) and also on post's border if possible

do you have an example to show us?

**Comment by hyperglass** [comment]
![Sun-Valley-Context-Menu-Example-4](https://user-images.githubusercontent.com/99114709/153775201-f296d66a-e3d0-482f-b7e5-eb5b783561c7.png)
The shadows at the border..


![image](https://user-images.githubusercontent.com/99114709/153775209-90266205-2933-49d6-99db-52a6086bd8bc.png)
Currently its merging with the background colour so its not proper visually.

**Comment by antoinekm** [comment]
> ![Sun-Valley-Context-Menu-Example-4](https://user-images.githubusercontent.com/99114709/153775201-f296d66a-e3d0-482f-b7e5-eb5b783561c7.png) The shadows at the border..
> 
> ![image](https://user-images.githubusercontent.com/99114709/153775209-90266205-2933-49d6-99db-52a6086bd8bc.png) Currently its merging with the background colour so its not proper visually.

and what is your proposal for people which have ``#000000`` theme

**Comment by hyperglass** [comment]
This can be specified on the basis of theme people are using, for `#191919`, increment in shadows can be implemented 
whereas for `#000000`, a white-ish-grey shadow can be added.. or else simple White borders can be implemented.
