### ISSUE TITLE
Replace header divider line with Shadows

### ISSUE THREAD

**Issue by hyperglass** [onRuntime/instagram-dark-extension#48]
from
![image](https://user-images.githubusercontent.com/99114709/153775459-7b617b11-090e-4129-ba77-eabdd8706598.png)
to
![image](https://user-images.githubusercontent.com/99114709/153775754-6dfb9437-9372-4cbf-8131-2f83510f0a5a.png)

**Comment by antoinekm** [comment]
With the current theme we dont see that but we will add this feature for the future themes selector
