### ISSUE TITLE
Replace Chevron Circle with a Better one

### ISSUE THREAD

**Issue by hyperglass** [onRuntime/instagram-dark-extension#51]
Replace the following sprite with one having a minimal look

**Comment by antoinekm** [comment]
> Replace the following sprite with one having a minimal look

Which chevron are you talking about ?

**Comment by hyperglass** [comment]
![image](https://user-images.githubusercontent.com/99114709/154338438-4e2da892-0acb-468b-862b-474e57f99cec.png)
Look at the quality of the white circle with arrow in it, compared to the textures of a photo below it..
Replace with a grey one if possible to make it look good for every theme be it light or dark instead of default white

**Comment by Johjoh-6** [comment]
Hi, mate. I've looked into this issue and the one you opened about another icon  ( in the issue #52 ) and I discovered that instagram used an old css technique (sprites) to display those icons you want me to change (See this link : [https://www.instagram.com/static/bundles/es6/sprite_core_2x_bcd90c1d4868.png/bcd90c1d4868.png] ), which unfortunately makes it impossible for us to change them. Sorry

**Comment by antoinekm** [comment]
We could but it's taking a lot of time btw we could edit this image and replace it or replace elements but yea its a lot of time for pretty much no changes for the ux
