### ISSUE TITLE
Fix Chevron Circles inside the Posts

### ISSUE THREAD

**Issue by hyperglass** [onRuntime/instagram-dark-extension#52]
![image](https://user-images.githubusercontent.com/99114709/154357500-bf07e0bf-adb4-4234-ad61-eecec975e502.png)

**Comment by Johjoh-6** [comment]
Hi, mate. I've looked into this issue and the one you opened about another icon  ( in the issue #51 ) and I discovered that instagram used an old css technique (called sprites) to display those icons you want me to change (See this link : [https://www.instagram.com/static/bundles/es6/sprite_core_2x_bcd90c1d4868.png/bcd90c1d4868.png] ), which unfortunately makes it impossible for us to change them. Sorry
